main-server-url: "http://ec2-54-152-150-232.compute-1.amazonaws.com:8080/api/v1/cam-watch/devices"
get-usb-device-script: "get-usb-device.ps1"
user-id: "40532dd0-d694-48cc-b432-bda9482b5f33"
device-local: "GoPresence - PC"
